name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false

      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

        include:
          - os: windows-latest
            configure_preset: windows-release
          - os: ubuntu-latest
            configure_preset: linux-release
          - os: macos-latest
            configure_preset: macos-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential pkg-config cmake ninja-build \
            libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev \
            libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev \
            libdbus-1-dev libibus-1.0-dev libudev-dev \
            libpipewire-0.3-dev libwayland-dev libdecor-0-dev

      - name: Configure CMake
        run: >
          cmake --preset ${{ matrix.configure_preset }}

      - name: Build
        run: >
          cmake --build build/${{ matrix.configure_preset }}
